version: "3.8"

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  backend:
    build:
      context: ./backend-b
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 5000:5000

  frontend:
    build:
      context: ./frontend-b
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    #env_file:
    #  - ./api/.env.stage.dev
